version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file: 
            - ./.env
        volumes:
            - ./app:/src
    db:
        image: mariadb:10
        restart: always
        ports:
            - '3307:3306'
        volumes:
          - ./db:/var/lib/mysql
        environment:
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    web:
        image: nginx:1.19.3-alpine
        restart: always
        ports:
            - 89:80
            - 4439:443
        depends_on:
            - app
            - db
            - redis
        volumes:
            - ./app:/src
            - ./web:/etc/nginx/conf.d
    redis:
        image: redis:6.0.8-alpine
        restart: always